DROP DATABASE IF EXISTS DBEXERCICIO27; 
CREATE DATABASE DBEXERCICIO27; 
USE DBEXERCICIO27; 

CREATE TABLE TAG (
IDTAG INT NOT NULL,
DESCRICAO VARCHAR(45),
IDENTIFICACAO VARCHAR(20),
PRIMARY KEY (IDTAG)
);

CREATE TABLE SEGURANCA (
IDSEGURANCA INT NOT NULL,
IDTAG INT NOT NULL,
NOME VARCHAR(20),
CARGO VARCHAR(15),
SOBRENOME VARCHAR(75),
DATANASCIMENTO DATE,
EMPRESA VARCHAR(20),
DTADMISSAO DATE,
PRIMARY KEY (IDSEGURANCA),
FOREIGN KEY (IDTAG) REFERENCES TAG (IDTAG)
 );
 
CREATE TABLE USUARIO (
IDUSUARIO INT NOT NULL,
NOME VARCHAR(30),
NOMEUSUARIO VARCHAR(20),
SENHA VARCHAR(25),
DTNASCIMENTO DATE,
SOBRENOME VARCHAR(75),
CPF INT,
PRIMARY KEY (IDUSUARIO)
);


CREATE TABLE LOCAL (
IDLOCAL INT NOT NULL,
DESCRICAO VARCHAR(100),
IDENTIFICACAO VARCHAR(20),
PRIMARY KEY (IDLOCAL)
);

CREATE TABLE GERENCIA (
IDUSUARIO INT NOT NULL,
IDSEGURANCA INT NOT NULL,
PRIMARY KEY (IDUSUARIO, IDSEGURANCA),
FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (IDUSUARIO),
FOREIGN KEY (IDSEGURANCA) REFERENCES SEGURANCA (IDSEGURANCA)
);

CREATE TABLE REGISTRO (
IDTAG INT NOT NULL,
IDLOCAL INT NOT NULL,
DATAREGISTRO DATETIME,
PRIMARY KEY (IDTAG, IDLOCAL),
FOREIGN KEY (IDTAG) REFERENCES TAG (IDTAG),
FOREIGN KEY (IDLOCAL) REFERENCES LOCAL (IDLOCAL)
);